name: Publish Packages

on:
  push:
    branches:
      - main
    tags:
      - '@arvore/*@*'

  workflow_dispatch:
    inputs:
      package:
        description: 'Package name to publish (e.g., @arvore/aws-secrets-manager-mcp)'
        required: false
      version:
        description: 'Version bump type (major, minor, patch)'
        required: false
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build all packages
        run: pnpm build

      - name: Publish all packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish specific package
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.package != ''
        run: |
          cd packages/$(echo ${{ github.event.inputs.package }} | cut -d'/' -f2 | sed 's/-mcp$//')
          pnpm version ${{ github.event.inputs.version }}
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

